- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: test
      location: westeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: test
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: test
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: test
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: test
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: consola9443
          protocol: Tcp
          destination_port_range: 9443
          access: Allow
          priority: 104
          direction: Inbound
        - name: consola9643
          protocol: Tcp
          destination_port_range: 9643
          access: Allow
          priority: 104
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: test
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: test
      name: VMtest
      vm_size: Standard_D2_v3
      admin_username: azureuser
      admin_password: Sevilla-2021.
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
