name: Stop PRO_EI
  hosts: localhost
  connection: local
  tasks:
    - name: Stop EI_01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2EI01
        allocated: no
    - name: Stop EI_02
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2EI02
        allocated: no
    - name: Stop EI_AN01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2AN01
        allocated: no

    - name: Stop IS_01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2IS01
        allocated: no
    - name: Stop IS_02
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2IS02
        allocated: no
    - name: Stop IS_AN02
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2AN02
        allocated: no

    - name: Stop APIM_01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2API01
        allocated: no
    - name: Stop APIM_02
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2API02
        allocated: no
    - name: Stop APIM_AN03
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2AN03
        allocated: no