name: Stop DES_EI
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: infracodesa
        name: INFRACODESWSO2EI01
        allocated: no