- name: Stop DES_IS
  hosts: localhost
  connection: local
  tasks:
    - name: Stop IS_01
      azure_rm_virtualmachine:
        resource_group: infracodesa
        name: INFRACODESWSO2IS01
        allocated: no