name: Stop DES_EI
  hosts: localhost
  connection: local
  tasks:
    - name: Stop EI_01
      azure_rm_virtualmachine:
        resource_group: infracodesa
        name: INFRACODESWSO2EI01
        allocated: no