- name: Start PRO_EI
  hosts: localhost
  connection: local
  tasks:
    - name: Start EI_01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2EI01
    - name: Start EI_02
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2EI02
    - name: Start EI_AN01
      azure_rm_virtualmachine:
        resource_group: infracoprod
        name: INFRACOPRODWSO2AN01