- name: Stop QA_IS
  hosts: localhost
  connection: local
  tasks:
    - name: Stop IS_01
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2IS01
        allocated: no
    - name: Stop IS_02
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2IS02
        allocated: no
    - name: Stop IS_AN02
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2AN02
        allocated: no