name: Start QA_IS
  hosts: localhost
  connection: local
  tasks:
    - name: Start IS_01
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2IS01
    - name: Start IS_02
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2IS02
    - name: Start IS_AN02
      azure_rm_virtualmachine:
        resource_group: infracoqa
        name: INFRACOQAWSO2AN02