---
- hosts: localhost
  tasks:
    - name: Deleting resource group - "test"
      azure_rm_resourcegroup:
        name: test
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg